### ISSUE TITLE
Missing XPlot.GoogleCharts.fsx

### ISSUE THREAD

**Issue by monkieboy** [fslaborg/XPlot#11]
When getting the package from Nuget the XPlot.GoogleCharts.fsx is not present.

It is located in version XPlot.GoogleCharts.1.1.6 in the packages directory but not in XPlot.GoogleCharts.1.1.8 version.

**Comment by TahaHachana** [comment]
I stopped bundling the bootstrapping script with the package since the migration to [ProjectScaffold](https://github.com/fsprojects/ProjectScaffold) and expect users to reference the dlls themselves.

Please also note that the functionality for displaying charts in a WPF window is now in a [separate package](http://www.nuget.org/packages/XPlot.GoogleCharts.WPF). This was necessary for the FsLab integration and a smooth cross-platform experience.

I'll update the documentation to reflect all these changes soon.

**Comment by monkieboy** [comment]
Thanks for the update.

**Comment by tpetricek** [comment]
I think having a load script for XPlot would still be nice - I added one to FsLab (which just opens the plot in a web browser). I'm sure we could figure out how to add it back to the `XPlot.GoogleCharts.WPF` package, at least! Though I'm not quite sure how to tell Paket to do this... 

@forki - we're using `Paket.Pack` here with this [paket.template](https://github.com/TahaHachana/XPlot/blob/master/src/XPlot.Plotly.WPF/paket.template) file (type=project), but we'd like to add one `fsx` file to the package. Do we need to switch to "type=file"? Or can we just add the file as "Content" in the project?

(That said, we could also say that the recommended way of getting XPlot for interactive scripting is through FsLab, which gives you easy loading & web-browser chart display... which could be improved - I opened https://github.com/fslaborg/FsLab/issues/89 for this)

**Comment by TahaHachana** [comment]
The [old loading script](https://github.com/TahaHachana/XPlot/blob/master/OldNuGet/XPlot.GoogleCharts/XPlot.GoogleCharts.fsx) references the necessary DLLs and warms up the JSON serialization but doesn't add an FSI printer that opens charts automatically.

I'll put it back in if this is straightforward to accomplish with Paket.

**Comment by tpetricek** [comment]
Sounds good - even just loading the DLLs makes things easier!

You can use something like the following to support both Paket and NuGet references:

    #I """../../packages/XPlot.GoogleCharts.1.1.6/Lib/Net45""" 
    #I """../../packages/XPlot.GoogleCharts/Lib/Net45""" 
    #r "XPlot.GoogleCharts.dll"

The #I works even if the directory does not exists - so this will work for both ways of referencing the library. (Also, please check that the lower-case/upper-case paths are correct for Mac/Linux support...)

**Comment by forki** [comment]
> but we'd like to add one fsx file to the package

no need to change to type=file.

**Comment by cartermp** [comment]
I'll close this older issue out. The easiest way to use XPlot is definitely the .NET jupyter kernel here: https://mybinder.org/v2/gh/dotnet/try/master?urlpath=lab

Using the package locally with FSI is like any other package, and eventually when `dotnet fsi` ships with `#r nuget` support it'll be trivial to use these packages from any arbitrary script.
