### ISSUE TITLE
Figure out a portable docs gen

### ISSUE THREAD

**Issue by cartermp** [fslaborg/XPlot#112]
Currently doc gen requires mono and mono tends to not make my very happy. It also just execs into FSI to run a script that also makes me not very happy. This will work fine on Windows with desktop FSI, but not on .NET Core.

**Comment by TheAngryByrd** [comment]
Please take ideas from from https://github.com/TheAngryByrd/MiniScaffold/pull/110

**Comment by cartermp** [comment]
Completed in https://github.com/fslaborg/XPlot/pull/137
