### ISSUE TITLE
Add Chart.Line overload taking seq<float>

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/XPlot#13]
In many cases, I just want to draw a simple line chart for a list of numbers:

```
let nums = [ 1.0; 3.0; 2.0; 2.5 ]
nums |> Chart.Line
```

This is currently not possible because `Chart.Line` takes `seq<#key * #value>`. I think for line charts, it makes a good sense to have a "simple" overload - this is annoying especially if you are getting the data from some other source as you'll end up writing a lot of:

```
nums 
|> Seq.mapi (fun idx v -> idx, v)
|> Chart.Line
```

I don't think we should have this for _all_ kinds of charts, but we should review & see where this makes sense.

**Comment by TahaHachana** [comment]
I think that an overload that takes a `seq<#value>` makes sense for the area, bar, column, line and scatter charts.

**Comment by tpetricek** [comment]
Yes, that sounds good! 

I'm helping with an F# hackathon in NYC next Saturday, so I can see if anybody would want to contribute :-). This sounds like a quite easy addition, so it would be a nice start for someone from the community!

**Comment by cartermp** [comment]
This works in the latest published XPlot.Plotly, at least certainly in the Jupyter kernel:
<img width="907" alt="image" src="https://user-images.githubusercontent.com/6309070/68498020-e78b5300-0223-11ea-9b1b-2a55cbf226a9.png">
