### ISSUE TITLE
documentation for palettes for heatmaps

### ISSUE THREAD

**Issue by thomasd3** [fslaborg/XPlot#136]
I can't find any documentation about how to set palettes, where / if there are presets, what the syntax it for the palettes, etc.

The code shows the colorscale parameter to be of the 'object' type, so it could be whatever and anything at the same time.

Is there any place where this is documented?

**Comment by cartermp** [comment]
Plotly colorscales are javascript objects, but also magic strings like `"RdBu"`. So the only decent representation of this is `obj`. This is documented on the plotly site pretty extensively: https://plotly.com/python/colorscales/#custom-heatmap-color-scale-with-graph-objects

Some examples in the tests are here: https://github.com/fslaborg/XPlot/blob/22037d9e7b1fd1d0ceed0b64c35a6942166de10b/tests/TestData/XPlot.Plotly/Heatmaps.fs#L33

I don't think Plotly has a documented list of the magic strings, but their source code does show them here: https://github.com/plotly/plotly.js/blob/master/src/components/colorscale/scales.js

There is also some plotly documentation about custom colorscales here: https://plotly.com/javascript/colorscales/

**Comment by cartermp** [comment]
The docs gen system for xplot uses some old tech that doesn't work on .NET Core, been looking to update it which I might try this week. Then it'll be a lot easier to add documentation

**Comment by thomasd3** [comment]
ok, got it, thanks!
