### ISSUE TITLE
Cannot get xplot render in VS Code

### ISSUE THREAD

**Issue by Curtis-64** [fslaborg/XPlot#162]
**Describe the bug**

I cannot get XPlot to render in the VS Code Insiders edition. I have tried importing the interactive (referencing prior bug) but nothing seems to work to get it to render inline.

**To Reproduce**

Tried the following
#i "nuget:https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json"
#r "nuget:xplot.plotly.interactive"

**Expected behavior**
I would like to see the widget/plot render inline.

**Screenshots**
I get a table view or rendering to an external browser.

**Other information:**
 - .NET version (core, framework, etc.)
 - Enviroment (jupyter notebooks, FSI, etc.)
 - Library version

Update: Oops! I think this should go in .NET Interactive GITHUB.

**Comment by cartermp** [comment]
Yeah, this is a .NET Interactive issue. You should not require the feed via `#i`, but it will fail in GA VSCode with an internal exception unless you save the notebook. But then it works:

![image](https://user-images.githubusercontent.com/6309070/112874807-38e5ed80-9078-11eb-9747-df41b7b1ba45.png)
