### ISSUE TITLE
xplot.plotly.interactive failed with the latest VS Code

### ISSUE THREAD

**Issue by kkartavenka** [fslaborg/XPlot#169]
With the update to the latest VS Code version, the nuget package `xplot.plotly.interactive` failed.

**To Reproduce**

1. Use Visual Studio Code 1.62.0 or 1.63.0-insider
2. Code:
``` 
#r "nuget:XPlot.Plotly"

#r "nuget:xplot.plotly.interactive" 
```

3. Run

**Expected behavior**
No errors since they were not with the previous version of VS Code.

**Output**

Loading extensions from XPlot.Plotly.Interactive.dll

Error: Microsoft.DotNet.Interactive.KernelExtensionLoadException: Failure loading Kernel Extension
---> System.MissingMethodException: Method not found: 'Microsoft.DotNet.Interactive.DisplayedValue Microsoft.DotNet.Interactive.KernelInvocationContextExtensions.Display(Microsoft.DotNet.Interactive.KernelInvocationContext, System.Object, System.String)'.
at XPlot.Plotly.Interactive.KernelExtension.Microsoft.DotNet.Interactive.IKernelExtension.OnLoadAsync(Kernel kernel)
at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembly(FileInfo assemblyFile, Kernel kernel, KernelInvocationContext context) in C:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 132
--- End of inner exception stack trace ---

If I re-run this code -- there will be no error, however instead of chart, I see a table with parameters (see screenshot).

**Screenshot**

![image](https://user-images.githubusercontent.com/45607880/140513293-e21bc0e2-2b6c-4292-ae29-de059b8f8fbb.png)

![image](https://user-images.githubusercontent.com/45607880/140513408-da10a53d-d2c8-477c-a418-641cb1820321.png)

**Other information:**
 - .NET 5.0.402
 - Enviroment (jupyter notebooks in Visual Studio Code)
 - Library version 4.0.3

**Comment by cartermp** [comment]
My guess here is the older version of the interactive dependency we pull in here. Will need an update.

Also note that `#r "nuget:xplot.plotly.interactive" ` should be the only one you need though, since xplot.plotly is a transitive dependency.

**Comment by Alkasai** [comment]
Same issue with `#r "nuget:Plotly.NET.Interactive, 2.0.0-preview.11"`
![image](https://user-images.githubusercontent.com/161976/140666489-075f1ce8-f040-400d-b861-6b053b3d2070.png)

**Comment by cartermp** [comment]
@kkartavenka @Alkasai can you try now? I updated dependencies and published a new set of packages.

**Comment by kkartavenka** [comment]
> @kkartavenka @Alkasai can you try now? I updated dependencies and published a new set of packages.

Perfect for both Visual Studio Code and Visual Studio Code Insider. Thank you!

**Comment by Alkasai** [comment]
> @kkartavenka @Alkasai can you try now? I updated dependencies and published a new set of packages.

Seems like `#r "nuget:XPlot.Plotly.Interactive"` installing correctly, but `#r "nuget:Plotly.NET.Interactive, 2.0.0-preview.11"` is still getting this error:
```
Loading extensions from Plotly.NET.Interactive.dll

Error: Microsoft.DotNet.Interactive.KernelExtensionLoadException: Failure loading Kernel Extension
---> System.MissingMethodException: Method not found: 'Microsoft.DotNet.Interactive.DisplayedValue Microsoft.DotNet.Interactive.KernelInvocationContextExtensions.Display(Microsoft.DotNet.Interactive.KernelInvocationContext, System.Object, System.String)'.
at Plotly.NET.Interactive.FormatterKernelExtension.Microsoft.DotNet.Interactive.IKernelExtension.OnLoadAsync(Kernel _arg1)
at Microsoft.DotNet.Interactive.Extensions.AssemblyBasedExtensionLoader.LoadFromAssembly(FileInfo assemblyFile, Kernel kernel, KernelInvocationContext context) in C:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Extensions\AssemblyBasedExtensionLoader.cs:line 132
--- End of inner exception stack trace ---
```

Not sure what is the different between the two libraries. Are they interchangeable? Should I be using the XPlot?

**Comment by kkartavenka** [comment]
I am not sure about the differences in teams/package of XPlot and Plotly.NET, therefore if that is necessarily to re-open the issue please do so.

**Comment by cartermp** [comment]
@Alkasai that's likely because plot.net doesn't have the updated dependency in that package. The two packages are unrelated.

I'm likely going to sunset this one soon, since plot.net has far more features.

**Comment by cartermp** [comment]
Looks like Plotly.NET updated to include the latest dependencies as well.
