### ISSUE TITLE
Missing Method Issue with 4.0.6

### ISSUE THREAD

**Issue by JasonBock** [fslaborg/XPlot#178]
**Describe the bug**
I just tried to run a notebook that uses the 4.0.6 version with the latest .NET Interactive version and I'm getting an error.

**To Reproduce**
1. Go to this repo: https://github.com/JasonBock/Collatz
2. Load the Demo.ipynb file in the Collatz directory
3. Try to run the code that loads the NuGet packages

**Expected behavior**
The packages load

**Screenshots**
I get this error:

```
Error: Failed to load kernel extension "KernelExtension" from assembly C:\Users\jason\.nuget\packages\xplot.plotly.interactive\4.0.6\interactive-extensions\dotnet\XPlot.Plotly.Interactive.dll
Error: Microsoft.DotNet.Interactive.KernelExtensionLoadException: Failure loading Kernel Extension
---> System.MissingMethodException: Method not found: 'Microsoft.DotNet.Interactive.DisplayedValue Microsoft.DotNet.Interactive.KernelInvocationContextExtensions.DisplayAs(Microsoft.DotNet.Interactive.KernelInvocationContext, System.String, System.String, System.String[])'.
at XPlot.Plotly.Interactive.KernelExtension.Microsoft.DotNet.Interactive.IKernelExtension.OnLoadAsync(Kernel kernel)
at Microsoft.DotNet.Interactive.App.PackageDirectoryExtensionLoader.LoadFromAssemblyFile(FileInfo assemblyFile, Kernel kernel, KernelInvocationContext context) in D:\a\_work\1\s\src\dotnet-interactive\PackageDirectoryExtensionLoader.cs:line 116
--- End of inner exception stack trace ---
```

**Other information:**
.NET Interactive

© 2020 Microsoft Corporation
Version: 1.0.425803+1db2979099d0272660e1497cae9b9af1238db42f
Library version: 1.0.0-beta.23258.3+1db2979099d0272660e1497cae9b9af1238db42f
Build date: 2023-05-17T01:00:47.7496054Z
https://github.com/dotnet/interactive

**Comment by JasonBock** [comment]
It seems like if I run it twice, it...."works", but then all I see is this instead of the chart:
![image](https://github.com/fslaborg/XPlot/assets/904213/0048720e-5664-4f33-b2f5-1204ffe3851c)

**Comment by JasonBock** [comment]
I've confirmed that if I install an earlier version of the Polygot Notebook extension in VSCode - Polyglot Notebooks v1.0.4102020 - everything works as expected.

**Comment by cartermp** [comment]
My guess is there's a breaking change under the covers with a .NET Interactive version? I imagine bumping the dependency in this repo (which hasn't changed in quite a long time) would do it. @colombod could you confirm?

**Comment by colombod** [comment]
There has been a lot of changes and a big refactoring on formatting. The real question is more about this project. Since there are official Nuget packages for fsharp from plotly would it not make more sense to converge efforts on those ones instead?

**Comment by jonsequitur** [comment]
It's likely a simple fix (as @cartermp said) which would give people with existing XPlot notebooks a way to not have to rewrite their code.

I'd definitely recommend any new code be written against the official Plotly.NET library.

**Comment by cartermp** [comment]
Oh yeah for sure. I can cut a release here though for folks who haven't moved over.

**Comment by JasonBock** [comment]
Oof, sorry, didn't realize that I should be using the Plotly stuff directly at this point 🙂

**Comment by cartermp** [comment]
No need to apologize! Use what works for you :)

I'll tee up a PR today and see if I can publish a new NuGet

**Comment by cartermp** [comment]
Okay, I published https://www.nuget.org/packages/XPlot.Plotly.Interactive/4.0.7 to use the latest interactive packages!

**Comment by zyzhu** [comment]
Thanks. I just noticed my notebook with XPlot was broken in the past week. It is fixed now.

**Comment by AmirUniPi** [comment]
How can I solve this problem? Could you please help me? 
![image](https://github.com/user-attachments/assets/8ed1e415-021f-4928-9c01-76083f3f5524)
