### ISSUE TITLE
Encode "\n" and other special characters

### ISSUE THREAD

**Issue by tpetricek** [fslaborg/XPlot#18]
The following generates invalid JavaScript:

```
[ ("\n", 42) ] |> Chart.Column
```

**Comment by cartermp** [comment]
This generates a plot without issue in a modern browser, so I'll close this out: 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/6309070/68498296-7f893c80-0224-11ea-9235-663deba7750a.png">
