### ISSUE TITLE
Default Sizes of Charts

### ISSUE THREAD

**Issue by drcrook1** [fslaborg/XPlot#34]
Default sizing of charts is set statically and by pixels.  I need the ability to have it inherit the properties of the encapsulating div and say minus 10%.

The defaults end up forcing me to do something along these lines: 
$(function () { $.get("http://fsharpcharttest2.azurewebsites.net/api/values/ScatterPlot", function (data, status) {  $("#FSharpChartDivTest_1").append(data); drawChart(); setTimeout( function(){ $("#FSharpChartDivTest_1 svg").css("transform", "scale(.7,.7) translateX(-20%)"); }, 4000); }); });

here is a sample: http://indiedevspot.com/2016/04/16/testing-charts/

**Comment by kflu** [comment]
The default size is also very problematic for use in fslab journal. I've created a PR to suppress presetting the default but rely on the user's choice: #44

**Comment by cartermp** [comment]
Closing this as it is mitigated significantly by #44 and does not appear to be an issue in Jupyter notebook environments.
