### ISSUE TITLE
Dependency Error on ver.1.4.1 by Newtonsoft.Json

### ISSUE THREAD

**Issue by iLikeSource** [fslaborg/XPlot#41]
Hello.
After being going to use ver.1.4.1, a run-time exception about the dependence occurred.
Ver.9.0.0 of Newtonsoft.Json was necessary, but was contents not to be found. I can find only after Ver.9.0.1 , the version of Newtonsoft.Json was not able to use 9.0.0.

After changing it in Ver.1.3.0 for trial, Ver.6.0.0 of Newtonsoft.Json be need this time. Therefore, after changing only the folder name of Newtonsoft.Json of the package folder to 6.0.0 for trial , I succeeded.

Is this a problem only for my environment?

**Comment by TahaHachana** [comment]
Hello,

This isn't specific to your environment, please try version 1.4.2 which has explicit dependencies versions.

**Comment by cartermp** [comment]
Closing as this is not likely to be relevant given the much newer version of these packages that use .NET Standard.
