### ISSUE TITLE
Loosen Newtonsoft.Json version restrictions for XPlot.Plotly

### ISSUE THREAD

**Issue by malisimo** [fslaborg/XPlot#51]
Currently version 1.4.2 of XPlot.Plotly lib requires Newtonsoft.Json version 9.0.1 **EXACTLY**.  Could you change this to be >= 9.0.1?  There is very little chance of having that one referenced by other assemblies, which makes this difficult to use where you want to pull in lots of references.
Thanks

**Comment by cartermp** [comment]
Closing as XPlot is going to be .NET Standard 2.0 only, where these kinds of versioning issues are generally not a problem
