### ISSUE TITLE
Non-English characters (ěščřžýáíé) are not supported? 

### ISSUE THREAD

**Issue by Klepeto** [fslaborg/XPlot#53]
`Chart.Line [1;2;3;4] |>Chart.WithXTitle("ěščřžýáíé")`
Becomes:
![image](https://cloud.githubusercontent.com/assets/8652069/25779603/f235f46e-331c-11e7-8210-2ea08636ea5a.png)

I am using Plotly chart with FSLab (maybe there is the problem).
Characters are displayed well in Plotly cloud.

**Comment by cartermp** [comment]
This displays correctly in a Jupyter environment. I imagine in modern browsers it would too.
<img width="912" alt="image" src="https://user-images.githubusercontent.com/6309070/68500147-e4469600-0228-11ea-87ae-a768dfa1813d.png">
