### ISSUE TITLE
The types in function signatures in docs are incorrectly rendered

### ISSUE THREAD

**Issue by mathias-brandewinder** [fslaborg/XPlot#62]
As an example, https://fslab.org/XPlot/reference/xplot-googlecharts-chart.html displays signatures such as
```
Annotation(data, Labels, Options)
Signature: (data:seq<'?7734> * Labels:seq<string> option * Options:Options option) -> GoogleChart
Type parameters: '?7734, 'V 
```

For instance, `seq<'?7734>` is incorrect.

**Comment by cartermp** [comment]
This doesn't appear to be an issue in the latest published docs.
