### ISSUE TITLE
Documentation updated in source but not webpage.

### ISSUE THREAD

**Issue by b0wter** [fslaborg/XPlot#66]
I was looking into plotting several series into a single chart and found [this](https://tahahachana.github.io/XPlot/chart/plotly-line-scatter-plots.html) on github.io.

After testing it and a quick [search](https://stackoverflow.com/questions/48330685/why-doesnt-this-xplot-plotly-code-compile) I found that this is old syntax and is no longer usable.

This error is already fixed in the [docsrc](https://github.com/fslaborg/XPlot/blob/master/docsrc/content/chart/plotly-box-plots.fsx) but not an the aforementioned site.

**Comment by tpetricek** [comment]
Is this really fixed in docsrc? 

Your links above are pointing at `plotly-box-plots.fsx` (in docsrc) and `plotly-line-scatter-plots.html` (in docs), which are different files - can you double check that we just need to regenerate the docs? If so, I can easily do that, but I suspect we might need to fix docs - if you were able to help, that would be amazing.

**Comment by b0wter** [comment]
I'll set myself a reminder to check this on the weekend.

**Comment by b0wter** [comment]
Found some time earlier. I've looked up the files:

[docs](https://github.com/fslaborg/XPlot/blob/master/docs/chart/plotly-line-scatter-plots.html)
[docsrc](https://github.com/fslaborg/XPlot/blob/master/docsrc/content/chart/plotly-line-scatter-plots.fsx)
[online](https://tahahachana.github.io/XPlot/chart/plotly-line-scatter-plots.html)

As you can see the docs match the docsrc but differ from what is online. Interestingly, the file in the repository contains the correct file from the beginning.

**Comment by tpetricek** [comment]
Doh! I see what's wrong now! The latest version is now hosted at: https://fslab.org/XPlot/chart/plotly-line-scatter-plots.html

I don't think there is an easy fix - but I'll send a PR to @TahaHachana's repo, so that the docs there are the same.

**Comment by tpetricek** [comment]
Uh, it looks like that's not possible, because the repo has been moved. So I guess we just have to wait until Google indexes the new site. Unless anyone knows of a good workaround for this?

**Comment by TahaHachana** [comment]
I added a robots.txt rule to disallow bots access to the old documentation, eventually it will drop off Google's index and make it favor the new one.

**Comment by tpetricek** [comment]
Nice trick! Thanks.
