### ISSUE TITLE
General documentation enhancement

### ISSUE THREAD

**Issue by awf** [fslaborg/XPlot#80]
It is great to be able to go to a specific example of a type of plot one might want and to then build on that.

For example, I want a 3D surface plot, so I go to e.g. 
https://fslab.org/XPlot/chart/plotly-3d-surface-plots.html, copy and paste code, and I'm good to go.

However, I now want to custom-scale the Z axis, and there's no navigable way to get there.

My proposal is that "Layout" in the code same is hyperlinked to an excellent reference for "Layout", which is much more F# specific than this: https://fslab.org/XPlot/reference/xplot-plotly-layout-layout.html

Apologies this isn't a PR, but in case I don't get round to it, putting it up as a nice-to-have

**Comment by cartermp** [comment]
@awf any appetite for a PR after ~1.1 years? 🙂

**Comment by cartermp** [comment]
(FWIW I intend on doing a big documentation pass after the repo is "clean" and some basics we need for the jupyter kernel are in place)

**Comment by mikaelletang** [comment]
If I may : for a total F#  newbie like me stumbling upon the lib to make a simple drawing, it might be worth adding  `|> Chart.Show` in the examples, just spent a few hours trying to figure out why I couldn't draw a thing :) (happy to do the PR, unless you've got a good reason for not having it)

**Comment by zyzhu** [comment]
New documentations are published with links to binder added on each chart demo. You may play it interactively on notebook directly now. More contents are welcome.
