### ISSUE TITLE
Scatter Plot in a Jupyter Notebook in C# is very slow

### ISSUE THREAD

**Issue by aslotte** [fslaborg/XPlot#88]
I've recently started testing out XPlot.Plotly for C# in a Jupyter Notebook.
I've noticied that creating a scatter plot takes a very long time for medium to large datasets, and not only that, it pushes Google Chrome to a halt as the graph is very large.

I can see this behavior even with datasets as small as 20-30 Mb (400,000 rows).
Is this a known issue?
Thanks!

**Comment by zyzhu** [comment]
Closed in https://github.com/dotnet/machinelearning/issues/4251#event-2685172943
Use `Graph.Scattergl` to speed up.
