### ISSUE TITLE
build.sh reports error on build

### ISSUE THREAD

**Issue by cartermp** [fslaborg/XPlot#92]
```
-> DocoptException: errors Error: Error in Argument 1 ('<>')
   Expecting: Command 'build', Command 'run', Flag '--help', Flag '--version' or
   ShortFlag '-h'
```

This is after running `sh build.sh` on a fresh clone of the project on macOS Catalina.

**Comment by zyzhu** [comment]
build.cmd works on my windows machine. But build.cmd and build.sh are not consistent. build.sh misses build parameter. Try `sh build.sh build` for now?

`dotnet fake "$@"`
vs
`dotnet fake build %*`

**Comment by cartermp** [comment]
`sh build.sh build` works for me. I'll look at making `build` the default.
